name: akawo_app
description: Pay Less, Buy More!.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.4.0
  path_provider_windows: ^0.0.4+1

  popup_menu: ^1.0.5
  social_share: ^2.0.5
  google_fonts: ^1.1.2
  flutter_login: ^1.0.14
  flutter:
    sdk: flutter
  splashscreen:

  cupertino_icons: ^1.0.0
  otp_screen: ^0.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:

    - images/
